import type { StaticImageData } from "next/image";

import intro from "@/public/images/screen_1.png";
import letter from "@/public/images/screen_2.png";
import stars from "@/public/images/screen_3.png";
import beforeBaby from "@/public/images/before_baby_screen.png";
import afterBaby from "@/public/images/after_baby_screen.png";
import soft from "@/public/images/predictions_background.png";
import constellation from "@/public/images/constellation_background.png";
import moon from "@/public/images/moon_background.png";
import finale from "@/public/images/background_final.png";

import interview1 from "@/public/images/baby_question_1.png";
import interview2 from "@/public/images/baby_question_2.png";
import interview3 from "@/public/images/baby_question_3.png";
// The artwork's own numbering: baby_question_5 is card 4, baby_question_4 is card 5.
import interview4 from "@/public/images/baby_question_5.png";
import interview5 from "@/public/images/baby_question_4.png";

// Generated by scripts/cutout-icons.mjs (background removed).
import coffee from "@/public/images/cutouts/survival_coffee.png";
import diapers from "@/public/images/cutouts/survival_diapers.png";
import pillow from "@/public/images/cutouts/survival_pillow.png";
import camera from "@/public/images/cutouts/survival_camera.png";
import heart from "@/public/images/cutouts/survival_heart.png";

// Generated by scripts/cutout-stars.mjs (star cut out of its background).
import starNanaNani from "@/public/images/cutouts/star_1.png";
import starDadaDadi from "@/public/images/cutouts/star_2.png";
import starMamzzNini from "@/public/images/cutouts/star_3.png";

import messageNanaNani from "@/public/images/message_1.png";
import messageDadaDadi from "@/public/images/message_2.png";
import messageMamzzNini from "@/public/images/message_3.png";

import momPose1 from "@/public/images/mom_pose_1.png";
import momPose2 from "@/public/images/mom_pose_2.png";
import momPose3 from "@/public/images/mom_pose_3.png";
import momPose4 from "@/public/images/mom_pose_4.png";

import dadPose1 from "@/public/images/dad_pose_1.png";
import dadPose2 from "@/public/images/dad_pose_2.png";
import dadPose3 from "@/public/images/dad_pose_3.png";
import dadPose4 from "@/public/images/dad_pose_4.png";

export type ImageSrc = StaticImageData | string | null;

export const backgrounds = { intro, letter, stars, beforeBaby, afterBaby, soft, constellation, moon, finale };

export const interviewCards = [interview1, interview2, interview3, interview4, interview5];

export const survivalIcons = { coffee, diapers, pillow, camera, heart };

// Painted stars shown on the "A Few Words from Your Stars" screen. Messages without one
// fall back to a drawn star with the message's emoji inside.
export const starPortraits: Record<"nanaNani" | "dadaDadi" | "mamzzNini", ImageSrc> = {
  nanaNani: starNanaNani,
  dadaDadi: starDadaDadi,
  mamzzNini: starMamzzNini,
};

// Caricature slots. Each one shows an emoji placeholder until you add an image
// (import it above, or use a "/images/..." path) and set it here.
export const assets: Record<"nanaNani" | "dadaDadi" | "mamzzNini", ImageSrc> = {
  nanaNani: messageNanaNani,
  dadaDadi: messageDadaDadi,
  mamzzNini: messageMamzzNini,
};

// Mumma and Daddy strike a different pose for each prediction question.
export const parentPoses = {
  Mumma: [momPose1, momPose2, momPose3, momPose4],
  Daddy: [dadPose1, dadPose2, dadPose3, dadPose4],
};
